name: parentalogi-api ci

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: parentalogi-api
      PORT: 3001
      NODE_ENV: test
      DB_TEST_USERNAME: ${{secrets.DB_TEST_USERNAME}}
      DB_TEST_PASSWORD: ${{secrets.DB_TEST_PASSWORD}}
      DB_TEST_HOSTNAME: https://icvmdev.duckdns.org
      DB_TEST_NAME: parentalogi_test
      DB_TEST_DIALECT: mysql
      EMAIL_USER: ${{secrets.EMAIL_USER}}
      EMAIL_PASS: ${{secrets.EMAIL_PASS}}
      API_DOMAIN: http://localhost:3001
      WEB_DOMAIN: http://localhost:3000
      ST_TEST_URI: https://icvmdev.duckdns.org/supertokens-test
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
